#!/usr/bin/env bash

# EKAM CLI - Global Installation Script
# Installs ekam-cli as a global command that uses the project's venv
# Usage: bash install-ekam-cli.sh [project-directory]

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Helper functions
print_header() {
    echo -e "\n${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}\n"
}

print_section() {
    echo -e "\n${CYAN}▶ $1${NC}"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

# Detect OS
detect_os() {
    if [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "win32" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
        echo "windows"
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        echo "macos"
    else
        echo "linux"
    fi
}

# Main installation
print_header "EKAM CLI - Global Installation"

# Get project directory
if [ -z "$1" ]; then
    SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
else
    SCRIPT_DIR="$(cd "$1" 2>/dev/null && pwd)" || {
        print_error "Invalid project directory: $1"
        exit 1
    }
fi

if [ ! -f "$SCRIPT_DIR/setup.sh" ]; then
    print_error "Project directory does not contain setup.sh"
    print_error "Expected: $SCRIPT_DIR/setup.sh"
    exit 1
fi

print_section "Validating project directory..."
print_success "Project directory: $SCRIPT_DIR"

# Check if venv exists
if [ ! -d "$SCRIPT_DIR/ekam-venv" ]; then
    print_error "Virtual environment not found at $SCRIPT_DIR/ekam-venv"
    echo -e "Please run ${YELLOW}bash $SCRIPT_DIR/setup.sh${NC} first"
    exit 1
fi

print_success "Virtual environment found"

# Determine installation location based on OS and permissions
OS=$(detect_os)
print_section "Detecting system configuration..."
print_success "OS: $OS"

# Determine install location
if [ "$OS" = "windows" ]; then
    # For Windows, use a batch file in a common location
    print_warning "Windows requires special setup"
    echo "Please manually add the following to your PATH environment variable:"
    echo -e "  ${YELLOW}$SCRIPT_DIR/venv/Scripts${NC}"
    echo
    echo "Then create a shortcut or use the application directly"
    exit 1
else
    # Unix-like systems
    INSTALL_DIR=""

    # Check if we have write access to /usr/local/bin
    if [ -w /usr/local/bin ]; then
        INSTALL_DIR="/usr/local/bin"
        print_success "Can write to /usr/local/bin"
    elif [ -w /usr/bin ]; then
        INSTALL_DIR="/usr/bin"
        print_success "Can write to /usr/bin"
    else
        # Check if user bin exists
        if mkdir -p "$HOME/.local/bin" 2>/dev/null; then
            INSTALL_DIR="$HOME/.local/bin"
            print_success "Using user-local bin: $INSTALL_DIR"

            # Check if ~/.local/bin is in PATH
            if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
                print_warning "~/.local/bin is not in your PATH"
                echo "Add this to your shell profile (~/.bashrc, ~/.zshrc, etc):"
                echo -e "  ${YELLOW}export PATH=\"\$HOME/.local/bin:\$PATH\"${NC}"
            fi
        else
            # Fallback: try with sudo
            print_section "Checking for sudo access..."
            if sudo -n true 2>/dev/null; then
                INSTALL_DIR="/usr/local/bin"
                print_success "Will use sudo for installation"
            else
                print_error "Cannot determine installation directory"
                echo "Please ensure one of the following:"
                echo "  1. Write access to /usr/local/bin"
                echo "  2. Write access to /usr/bin"
                echo "  3. Write access to ~/.local/bin"
                echo "  4. Sudo access"
                exit 1
            fi
        fi
    fi
fi

# Create wrapper script
print_section "Creating wrapper script..."

WRAPPER_SCRIPT="$INSTALL_DIR/ekam-cli"
WRAPPER_CONTENT="#!/usr/bin/env bash
# EKAM CLI Wrapper
# This script activates the project's virtual environment and runs the application
# Auto-generated by install-ekam-cli.sh

PROJECT_DIR=\"$SCRIPT_DIR\"
VENV_DIR=\"\$PROJECT_DIR/ekam-venv\"

# Check if venv exists
if [ ! -d \"\$VENV_DIR\" ]; then
    echo \"Error: Virtual environment not found at \$VENV_DIR\"
    echo \"Please run: bash \$PROJECT_DIR/setup.sh\"
    exit 1
fi

# Detect OS for activation script
if [[ \"\$OSTYPE\" == \"msys\" ]] || [[ \"\$OSTYPE\" == \"win32\" ]] || [[ \"\$OSTYPE\" == \"cygwin\" ]]; then
    ACTIVATE=\"\$VENV_DIR/Scripts/activate\"
else
    ACTIVATE=\"\$VENV_DIR/bin/activate\"
fi

# Change to project directory to find config.yaml and .env
cd \"\$PROJECT_DIR\" || exit 1

# Activate and run
source \"\$ACTIVATE\"
python -m src.core.app \"\$@\"
EXIT_CODE=\$?
deactivate 2>/dev/null || true
exit \$EXIT_CODE
"

# Determine if we need sudo
USE_SUDO=""
if [ ! -w "$INSTALL_DIR" ]; then
    USE_SUDO="sudo"
    print_warning "Using sudo for installation"
fi

# Install wrapper script
if [ -n "$USE_SUDO" ]; then
    echo "$WRAPPER_CONTENT" | $USE_SUDO tee "$WRAPPER_SCRIPT" > /dev/null
    $USE_SUDO chmod +x "$WRAPPER_SCRIPT"
else
    echo "$WRAPPER_CONTENT" > "$WRAPPER_SCRIPT"
    chmod +x "$WRAPPER_SCRIPT"
fi

if [ -f "$WRAPPER_SCRIPT" ] && [ -x "$WRAPPER_SCRIPT" ]; then
    print_success "Wrapper script installed at $WRAPPER_SCRIPT"
else
    print_error "Failed to install wrapper script"
    exit 1
fi

# Verify installation
print_section "Verifying installation..."
if command -v ekam-cli &> /dev/null; then
    print_success "ekam-cli is now available in your PATH"
    echo
    echo -e "${GREEN}Installation complete!${NC}"
    echo
    echo -e "${CYAN}You can now use:${NC}"
    echo -e "  ${YELLOW}ekam-cli${NC}     - Run the application"
    echo -e "  ${YELLOW}ekam-cli --help${NC}  - Show help (if supported)"
    echo
else
    print_warning "ekam-cli not found in PATH yet"

    if [ "$INSTALL_DIR" = "$HOME/.local/bin" ]; then
        echo "You may need to add ~/.local/bin to your PATH:"
        echo -e "  ${YELLOW}export PATH=\"\$HOME/.local/bin:\$PATH\"${NC}"
        echo
        echo "Then reload your shell:"
        echo -e "  ${YELLOW}exec \$SHELL${NC}"
    fi
fi

echo -e "${CYAN}Additional Information:${NC}"
echo "  Project directory: $SCRIPT_DIR"
echo "  Wrapper location: $WRAPPER_SCRIPT"
echo "  Virtual environment: $SCRIPT_DIR/ekam-venv"
echo
echo -e "${CYAN}To uninstall ekam-cli:${NC}"
if [ -n "$USE_SUDO" ]; then
    echo -e "  ${YELLOW}sudo rm $WRAPPER_SCRIPT${NC}"
else
    echo -e "  ${YELLOW}rm $WRAPPER_SCRIPT${NC}"
fi
echo
